pull_request_rules:
  - name: Automatically merge dependencies
    conditions:
      - base=master
      - label=dependencies
    actions:
      merge:
        strict: true
      delete_head_branch: {}
